require('../electron/media-protocol');
'use strict';
const {app,dialog}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {fixture}=require('./test-docx.cjs');
app.setPath('userData',path.join(os.tmpdir(),'word-ui-'+process.pid));
let server;
const timeout=setTimeout(()=>{console.error('Word UI test timed out');app.exit(1);},40000);
(async()=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'word-ui-files-'));
  const original=await fixture();await fs.writeFile(path.join(root,'sample.docx'),original);await fs.writeFile(path.join(root,'note.md'),'# Markdown still works');
  server=await (await import('./mock-webdav.mjs')).startWebDAVServer(root);
  const ready=new Promise(resolve=>app.once('browser-window-created',(_event,win)=>{win.hide();win.webContents.once('did-finish-load',()=>resolve(win));}));
  require('../electron/main');const win=await ready;win.webContents.setBackgroundThrottling(false);
  const js=code=>win.webContents.executeJavaScript(code);
  const idle=async()=>{const deadline=Date.now()+8000;while(await js('state.busy')){if(Date.now()>deadline)throw Error('Action timed out');await new Promise(r=>setTimeout(r,20));}};
  await js('connUrl.value='+JSON.stringify('http://127.0.0.1:'+server.port)+';runAction(doConnect)');
  await js('runAction(()=>openFile({path:"/sample.docx",name:"sample.docx"}))');
  assert.equal(await js('state.currentFile.kind'), 'docx');
  assert.equal(await js('document.getElementById("wordPane").hidden'), false);
  assert.equal(await js('document.getElementById("markdownPanes").style.display'), 'none');
  assert.equal(await js('document.getElementById("viewMode").style.display'), 'none');
  assert.equal(await js('document.querySelectorAll(".word-protected").length'),2);
  async function typeFirst(text){
    await js('(()=>{const p=document.querySelector(".word-paragraph");p.focus();const range=document.createRange();range.selectNodeContents(p);getSelection().removeAllRanges();getSelection().addRange(range);document.execCommand("insertText",false,'+JSON.stringify(text)+');})()');
  }
  await typeFirst('Hello 编辑后的文字 world');
  assert.equal(await js('isDirty()'),true);
  await js('document.getElementById("wordAlign").value="center";document.getElementById("wordAlign").dispatchEvent(new Event("change"));document.getElementById("wordLine").value="2";document.getElementById("wordLine").dispatchEvent(new Event("change"));document.getElementById("wordIndent").click()');
  assert.equal(await js('document.querySelector(".word-paragraph").style.textAlign'),'center');
  await js('document.getElementById("wordAddParagraph").click()');
  assert.equal(await js('document.querySelectorAll(".word-paragraph").length'),3);
  await js('document.getElementById("wordDeleteParagraph").click()');
  assert.equal(await js('document.querySelectorAll(".word-paragraph").length'),2);
  await js('document.getElementById("wordUndo").click()');
  assert.equal(await js('document.querySelectorAll(".word-paragraph").length'),3);
  await js('document.getElementById("wordRedo").click()');
  assert.equal(await js('document.querySelectorAll(".word-paragraph").length'),2);
  await js('(()=>{const p=document.querySelector(".word-paragraph");p.focus();const r=document.createRange();r.selectNodeContents(p);r.collapse(false);getSelection().removeAllRanges();getSelection().addRange(r);p.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}));})()');
  assert.equal(await js('document.querySelectorAll(".word-paragraph").length'),3,'Enter splits a paragraph');
  await js('document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"Backspace",bubbles:true,cancelable:true}))');
  assert.equal(await js('document.querySelectorAll(".word-paragraph").length'),2,'Backspace merges adjacent paragraphs');
  await js('document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",shiftKey:true,bubbles:true,cancelable:true}))');
  assert.equal(await js('document.querySelectorAll(".word-paragraph").length'),2,'Shift Enter stays in the same paragraph');
  await js('document.getElementById("wordUndo").click()');
  await js('document.dispatchEvent(new KeyboardEvent("keydown",{key:"s",ctrlKey:true}))');await idle();
  assert.equal(await js('isDirty()'),false);
  const saved=await fs.readFile(path.join(root,'sample.docx'));
  const model=await require('../electron/docx').inspectDocx(saved);
  assert.equal(model.blocks[0].text,'Hello 编辑后的文字 world');
  assert.equal(model.blocks[0].format.align,'center');assert.equal(model.blocks[0].format.line,2);assert.equal(model.blocks[0].format.indent,24);
  await js('runAction(()=>openFile({path:"/note.md",name:"note.md"}))');
  assert.equal(await js('document.getElementById("wordPane").hidden'),true);
  assert.equal(await js('editorEl.value'),'# Markdown still works');
  await js('runAction(()=>openFile({path:"/sample.docx",name:"sample.docx"}))');
  assert.match(await js('document.querySelector(".word-paragraph").textContent'),/编辑后的文字/);
  await typeFirst('保留未保存修改');
  await fs.writeFile(path.join(root,'sample.docx'),original);
  await js('document.getElementById("wordSave").click()');await idle();
  assert.equal(await js('state.saveError && isDirty()'),true);
  assert.equal(await js('document.querySelector(".word-paragraph").textContent'),'保留未保存修改');
  assert.deepEqual(await fs.readFile(path.join(root,'sample.docx')),original);
  dialog.showMessageBox=async()=>({response:0});
  await js('runAction(()=>openFile({path:"/note.md",name:"note.md"}))');
  assert.equal(await js('state.currentFile.kind'),'docx','canceling failed-save navigation keeps document');
  await fs.writeFile(path.join(root,'sample.docx'),saved);
  await js('document.getElementById("wordSave").click()');await idle();assert.equal(await js('isDirty()'),false);
  await js('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
  await fs.mkdir(path.join(__dirname,'../.electron-cache'),{recursive:true});
  await fs.writeFile(path.join(__dirname,'../.electron-cache/word-editor.png'),(await win.webContents.capturePage()).toPNG());
  console.log('Word UI checks passed: single editing pane, native typing, paragraph formatting/add/delete, undo/redo, Ctrl+S, round-trip reopen, Markdown switching and conflict protection');
  clearTimeout(timeout);await server.close();app.exit(0);
})().catch(async error=>{console.error(error);clearTimeout(timeout);if(server)await server.close();app.exit(1);});
