// Real Electron + local WebDAV end-to-end check. Captures the implemented UI.
const { app, BrowserWindow, Menu, dialog } = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
app.setPath('userData', path.join(os.tmpdir(), 'md-ui-test-' + process.pid));
app.commandLine.appendSwitch('no-sandbox');
app.disableHardwareAcceleration();
const sample = '# 设计原则\n\n> 让阅读专注，让写作自然。\n\n## 少一点干扰，多一点专注\n\n好的工具应当安静地陪伴思考。\n把空间留给内容，把复杂留给系统。\n\n## 我们关注什么\n\n- 清晰的内容层级\n- 舒适的阅读节奏\n- 可靠的保存体验\n\n## 下一步\n\n- [x] 梳理核心流程\n- [ ] 完善编辑体验\n- [ ] 打磨视觉细节\n';
let server, root, timeout;
(async () => {
  root = await fs.mkdtemp(path.join(os.tmpdir(), 'md-ui-files-'));
  await fs.mkdir(path.join(root, '产品设计'));
  await fs.mkdir(path.join(root, '产品设计', '参考资料'));
  await fs.writeFile(path.join(root, '产品设计', '设计原则.md'), sample);
  await fs.writeFile(path.join(root, '产品设计', '交互说明.md'), '# 交互说明');
  await fs.writeFile(path.join(root, '产品设计', '更新日志.md'), '# 更新日志');
  const { startWebDAVServer } = await import('./mock-webdav.mjs');
  server = await startWebDAVServer(root);
  timeout = setTimeout(() => { console.error('UI test timed out'); app.exit(1); }, 20000);
  let primaryWindow;
  app.on('browser-window-created', (_event, win) => {
    if (primaryWindow) return;
    primaryWindow = win;
    win.webContents.once('did-finish-load', async () => {
      try {
        await win.webContents.executeJavaScript(`(async () => {
          connUrl.value = ${JSON.stringify('http://127.0.0.1:') } + ${server.port};
          connUser.value = 'test'; connPass.value = 'test';
          await runAction(doConnect);
          await navigate('/产品设计');
          await runAction(() => openFile({ path: '/产品设计/设计原则.md', name: '设计原则.md' }));
          editorEl.value += '\\n'; editorEl.dispatchEvent(new Event('input'));
          const before = editorEl.value;
          editorEl.setSelectionRange(2, 6);
          applyFormat('bold');
          if (!editorEl.value.startsWith('# **设计原则**')) throw new Error('Bold insertion failed');
          document.execCommand('undo');
          if (editorEl.value !== before) throw new Error('Format undo failed');
          editorEl.setSelectionRange(2, 6);
          applyFormat('link');
          if (editorEl.value.slice(editorEl.selectionStart, editorEl.selectionEnd) !== 'https://') throw new Error('Link selection failed');
          document.execCommand('undo');
          if (editorEl.value !== before) throw new Error('Link undo failed');
          editorEl.setSelectionRange(2, 6);
          applyFormat('color:#aa3322');
          renderPreview();
          if (getComputedStyle(previewEl.querySelector('span')).color !== 'rgb(170, 51, 34)') throw new Error('Text color preview failed');
          document.execCommand('undo');
          if (editorEl.value !== before) throw new Error('Color undo failed');
          const safe = window.sanitizeMarkdownHTML('<span style="font-family:KaiTi,serif;color:#aa3322;position:fixed;font-size:18px">正文</span>');
          if (!safe.includes('font-family') || !safe.includes('color') || safe.includes('position')) throw new Error('Typography sanitization failed');
        })()`);
        await win.webContents.executeJavaScript(`new Promise((resolve, reject) => {
          const deadline = Date.now() + 8000;
          function check() {
            if (!isDirty() && !state.busy) return resolve();
            if (Date.now() > deadline) return reject(new Error('Auto-save timed out'));
            setTimeout(check, 100);
          }
          check();
        })`);
        assert.equal(await win.webContents.executeJavaScript("window.mdAPI.loadConnection().then(res => res.ok && res.data?.password === 'test')"), true, 'encrypted password can be restored');
        assert.equal((await fs.readFile(path.join(app.getPath('userData'), 'connection.enc'))).includes(Buffer.from('"password"')), false);
        assert.equal(await fs.readFile(path.join(root, '产品设计', '设计原则.md'), 'utf8'), sample + '\n');
        const check = await win.webContents.executeJavaScript(`({ dirty: isDirty(), text: dirtyEl.textContent, draft: readDraft(state.currentFile.path), noSaveButton: !document.getElementById('saveBtn'), overflow: document.documentElement.scrollWidth > window.innerWidth })`);
        assert.equal(check.dirty, false);
        assert.equal(check.draft, null);
        assert.equal(check.noSaveButton, true);
        assert.equal(check.overflow, false);
        await fs.mkdir(path.join(__dirname, '../output'), { recursive: true });
        await fs.writeFile(path.join(__dirname, '../output/md-browser-ui.png'), (await win.webContents.capturePage()).toPNG());
        win.setSize(960, 600);
        await new Promise(resolve => setTimeout(resolve, 200));
        assert.equal(await win.webContents.executeJavaScript('document.documentElement.scrollWidth > window.innerWidth'), false);
        await fs.writeFile(path.join(__dirname, '../output/md-browser-ui-compact.png'), (await win.webContents.capturePage()).toPNG());
        // Select a native menu action deterministically, then use the real directory picker.
        const originalMenu = Menu.buildFromTemplate;
        Menu.buildFromTemplate = template => ({ popup: () => template.find(entry => entry.label === '移动到…').click() });
        await win.webContents.executeJavaScript(`document.querySelector('.file-row.active').dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, cancelable: true }));`);
        await new Promise(resolve => setTimeout(resolve, 150));
        assert.equal(await win.webContents.executeJavaScript("document.getElementById('moveDialog').open"), true);
        await win.webContents.executeJavaScript("document.getElementById('moveConfirm').click()");
        await new Promise(resolve => setTimeout(resolve, 200));
        assert.equal(await fs.readFile(path.join(root, '设计原则.md'), 'utf8'), sample + '\n');
        assert.equal(await win.webContents.executeJavaScript('state.currentFile.path'), '/设计原则.md');
        Menu.buildFromTemplate = originalMenu;
        const originalDialog = dialog.showMessageBox;
        dialog.showMessageBox = async () => ({ response: 1 });
        await win.webContents.executeJavaScript('runAction(deleteCurrent)');
        assert.equal(await win.webContents.executeJavaScript('state.currentFile'), null);
        await assert.rejects(fs.access(path.join(root, '设计原则.md')));
        dialog.showMessageBox = originalDialog;
        const originalOpenDialog = dialog.showOpenDialog;
        const inputFile = path.join(root, 'input.txt');
        await fs.writeFile(inputFile, '# 导入验证\n\n中文文本。\n');
        dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [inputFile] });
        await win.webContents.executeJavaScript('window.importRun = runAction(importDocument); void 0');
        await new Promise(resolve => setTimeout(resolve, 150));
        await win.webContents.executeJavaScript("document.getElementById('nameInput').value = '笔记.md'; document.getElementById('nameForm').requestSubmit(document.querySelector('#nameForm [value=ok]'));");
        await win.webContents.executeJavaScript('window.importRun');
        assert.equal(await fs.readFile(path.join(root, '产品设计', '笔记.md'), 'utf8'), '# 导入验证\n\n中文文本。\n');
        // Importing the same name asks again and preserves the existing file.
        await win.webContents.executeJavaScript('window.importRun = runAction(importDocument); void 0');
        await new Promise(resolve => setTimeout(resolve, 150));
        await win.webContents.executeJavaScript("document.getElementById('nameInput').value = '笔记.md'; document.getElementById('nameForm').requestSubmit(document.querySelector('#nameForm [value=ok]'));");
        await new Promise(resolve => setTimeout(resolve, 150));
        assert.equal(await win.webContents.executeJavaScript("document.getElementById('nameInput').value"), '笔记（导入）.md');
        await win.webContents.executeJavaScript("document.getElementById('nameForm').requestSubmit(document.querySelector('#nameForm [value=ok]'));");
        await win.webContents.executeJavaScript('window.importRun');
        await fs.access(path.join(root, '产品设计', '笔记（导入）.md'));
        dialog.showOpenDialog = originalOpenDialog;
        const originalSaveDialog = dialog.showSaveDialog;
        const exportedPath = path.join(root, 'export.pdf');
        dialog.showSaveDialog = async () => ({ canceled: false, filePath: exportedPath });
        await win.webContents.executeJavaScript('runAction(exportCurrentPDF)');
        assert.equal((await fs.readFile(exportedPath)).subarray(0, 5).toString(), '%PDF-');
        dialog.showSaveDialog = originalSaveDialog;
        dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [exportedPath] });
        await win.webContents.executeJavaScript('window.importRun = runAction(importDocument); void 0');
        await new Promise(resolve => setTimeout(resolve, 150));
        assert.equal(await win.webContents.executeJavaScript("document.getElementById('nameInput').value"), 'export.pdf');
        await win.webContents.executeJavaScript("document.getElementById('nameForm').requestSubmit(document.querySelector('#nameForm [value=ok]'));");
        await win.webContents.executeJavaScript('window.importRun');
        assert.deepEqual(await fs.readFile(path.join(root, '产品设计', 'export.pdf')), await fs.readFile(exportedPath), 'PDF import preserves all bytes');
        assert.equal(await win.webContents.executeJavaScript("state.currentFile.kind === 'pdf' && !document.getElementById('pdfPane').hidden && editorEl.readOnly && document.getElementById('exportPdf').disabled"), true);
        await new Promise(resolve => setTimeout(resolve, 1500));
        await fs.writeFile(path.join(__dirname, '../output/pdf-preview.png'), (await win.webContents.capturePage()).toPNG());
        assert.equal(await win.webContents.executeJavaScript("!document.getElementById('pdfAnnotationPanel').hidden"),true,'PDF opens directly into reading and annotation');
        for (let i=0; i<100 && await win.webContents.executeJavaScript('state.busy'); i++) await new Promise(r=>setTimeout(r,100));
        assert.equal(await win.webContents.executeJavaScript("!document.getElementById('pdfAnnotationPanel').hidden && document.getElementById('pdfPageCanvas').width > 0"), true);
        await win.webContents.executeJavaScript(`(() => {
          const span=[...document.querySelectorAll('#pdfTextLayer span')].find(s=>s.textContent.trim());
          const range=document.createRange();range.selectNodeContents(span);
          getSelection().removeAllRanges();getSelection().addRange(range);
          document.dispatchEvent(new Event('selectionchange'));
        })()`);
        assert.equal(await win.webContents.executeJavaScript("document.getElementById('pdfSelectionToolbar').hidden"),false,'selection opens floating toolbar');
        assert.equal(await win.webContents.executeJavaScript("document.querySelector('.pdf-tools') === null && document.getElementById('viewMode').style.display === 'none'"),true,'no persistent top toolbar for PDF');
        const selectedText=await win.webContents.executeJavaScript('getSelection().toString()');
        const {clipboard}=require('electron');const originalWriteText=clipboard.writeText;let copiedText;
        clipboard.writeText=text=>{copiedText=text;};
        try {
          await win.webContents.executeJavaScript("document.getElementById('pdfTextCopy').onclick()");
          assert.equal(copiedText,selectedText,'copies exact selection through native clipboard');
        } finally {clipboard.writeText=originalWriteText;}
        await win.webContents.executeJavaScript("document.dispatchEvent(new Event('selectionchange'))");
        await fs.writeFile(path.join(__dirname,'../output/pdf-floating-toolbar.png'),(await win.webContents.capturePage()).toPNG());
        await win.webContents.executeJavaScript("getSelection().removeAllRanges();document.dispatchEvent(new Event('selectionchange'))");
        assert.equal(await win.webContents.executeJavaScript("document.getElementById('pdfSelectionToolbar').hidden"),true,'collapsed selection hides toolbar');
        await win.webContents.executeJavaScript(`(() => {
          const spans=[...document.querySelectorAll('#pdfTextLayer span')].filter(s=>s.textContent.trim());
          const secondLine=spans.find(s=>s.getBoundingClientRect().top>spans[0].getBoundingClientRect().bottom+5);
          if(!secondLine)throw new Error('Missing selectable PDF text');
          const range=document.createRange();range.setStart(spans[0].firstChild,0);range.setEnd(secondLine.firstChild,secondLine.textContent.length);
          const selection=getSelection();selection.removeAllRanges();selection.addRange(range);
          document.getElementById('pdfTextHighlight').click();
          const second=document.createRange();second.selectNodeContents(secondLine);selection.addRange(second);
          document.getElementById('pdfTextUnderline').click();
        })()`);
        const initialWidth=await win.webContents.executeJavaScript("document.getElementById('pdfPageCanvas').width");
        await win.webContents.executeJavaScript("document.getElementById('pdfZoomIn').click()");
        for(let i=0;i<100 && await win.webContents.executeJavaScript('state.busy');i++)await new Promise(r=>setTimeout(r,50));
        assert.ok(await win.webContents.executeJavaScript("document.getElementById('pdfPageCanvas').width")>initialWidth,'reader zoom increases rendering resolution');
        assert.equal(await win.webContents.executeJavaScript('window.pdfAnnotations.dirty()'),true,'zoom preserves annotations');
        await win.webContents.executeJavaScript("document.getElementById('pdfZoomFit').click()");
        for(let i=0;i<100 && await win.webContents.executeJavaScript('state.busy');i++)await new Promise(r=>setTimeout(r,50));
        assert.equal(await win.webContents.executeJavaScript("document.getElementById('pdfPageCanvas').width"),initialWidth,'fit width restored');
        await fs.writeFile(path.join(__dirname,'../output/pdf-text-selection.png'),(await win.webContents.capturePage()).toPNG());
        const oldMessageBox=dialog.showMessageBox;
        dialog.showMessageBox=async()=>({response:0});
        assert.equal(await win.webContents.executeJavaScript('canDiscard()'), false, 'cancel protects unsaved annotations');
        const webdav=require('../electron/webdav'),writePDF=webdav.writePDF;
        webdav.writePDF=async()=>{throw new Error('模拟网络中断');};
        try {await win.webContents.executeJavaScript('runAction(save)');assert.equal(await win.webContents.executeJavaScript('window.pdfAnnotations.dirty()'),true,'failed write retains edits');}
        finally {webdav.writePDF=writePDF;}
        dialog.showMessageBox=oldMessageBox;
        await win.webContents.executeJavaScript("document.getElementById('pdfClearAnnotations').click()");
        for(let i=0;i<100 && await win.webContents.executeJavaScript('state.busy');i++)await new Promise(r=>setTimeout(r,50));
        assert.equal(await win.webContents.executeJavaScript("document.getElementById('pdfClearAnnotations').disabled"),true,'clear removes all annotation objects');
        await win.webContents.executeJavaScript("document.dispatchEvent(new KeyboardEvent('keydown',{key:'z',metaKey:true,bubbles:true}))");
        for(let i=0;i<100 && await win.webContents.executeJavaScript('state.busy');i++)await new Promise(r=>setTimeout(r,50));
        assert.equal(await win.webContents.executeJavaScript("document.getElementById('pdfClearAnnotations').disabled"),false,'shortcut undoes clear');
        const annotatedPath=path.join(__dirname,'../output/pdf/annotations-check.pdf');
        const remotePDF=path.join(root,'产品设计','export.pdf');
        await win.webContents.executeJavaScript('runAction(save)');
        assert.equal(await win.webContents.executeJavaScript('window.pdfAnnotations.dirty()'),false);
        await fs.copyFile(remotePDF,annotatedPath);
        const { PDFDocument, PDFName, PDFArray, PDFDict }=require('pdf-lib');
        const annotatedDocument=await PDFDocument.load(await fs.readFile(annotatedPath));
        const annots=annotatedDocument.getPage(0).node.lookup(PDFName.of('Annots'),PDFArray);
        assert.equal(annots.size(),2,'native text markup objects');
        assert.equal(annots.lookup(0,PDFDict).get(PDFName.of('Subtype')).toString(),'/Highlight');
        assert.equal(annots.lookup(1,PDFDict).get(PDFName.of('Subtype')).toString(),'/Underline');
        assert.ok(annots.lookup(0,PDFDict).lookup(PDFName.of('QuadPoints'),PDFArray).size()>=16,'multi-line quads');

        await win.webContents.executeJavaScript('runAction(save)');
        assert.notDeepEqual(await fs.readFile(remotePDF),await fs.readFile(exportedPath),'saves directly over source PDF');
        await win.webContents.executeJavaScript("runAction(()=>openFile({path:'/产品设计/export.pdf',name:'export.pdf'}))");
        await win.webContents.executeJavaScript(`(()=>{
          getSelection().removeAllRanges();
          const span=[...document.querySelectorAll('#pdfTextLayer span')].find(s=>s.textContent.trim()),r=span.getBoundingClientRect(),layer=document.getElementById('pdfTextLayer');
          layer.dispatchEvent(new PointerEvent('pointerdown',{clientX:r.left+r.width/2,clientY:r.top+r.height/2,bubbles:true}));
          layer.dispatchEvent(new PointerEvent('pointerup',{clientX:r.left+r.width/2,clientY:r.top+r.height/2,bubbles:true}));
        })()`);
        await new Promise(r=>setTimeout(r,100));
        assert.equal(await win.webContents.executeJavaScript("!document.getElementById('pdfSelectionToolbar').hidden && !document.getElementById('pdfDeleteAnnotation').hidden"),true,'saved annotation is selectable');
        await win.webContents.executeJavaScript("document.getElementById('pdfDeleteAnnotation').click()");
        for(let i=0;i<100 && await win.webContents.executeJavaScript('state.busy');i++)await new Promise(r=>setTimeout(r,50));
        await win.webContents.executeJavaScript('runAction(save)');
        let changed=await PDFDocument.load(await fs.readFile(remotePDF));
        assert.equal(changed.getPage(0).node.lookup(PDFName.of('Annots'),PDFArray).size(),1,'deletes saved annotation');
        await win.webContents.executeJavaScript("document.dispatchEvent(new KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true}))");
        for(let i=0;i<100 && await win.webContents.executeJavaScript('state.busy');i++)await new Promise(r=>setTimeout(r,50));
        await win.webContents.executeJavaScript('runAction(save)');
        changed=await PDFDocument.load(await fs.readFile(remotePDF));
        assert.equal(changed.getPage(0).node.lookup(PDFName.of('Annots'),PDFArray).size(),2,'undo restores deleted saved annotation');
        await win.webContents.executeJavaScript("document.getElementById('pdfClearAnnotations').click()");
        for(let i=0;i<100 && await win.webContents.executeJavaScript('state.busy');i++)await new Promise(r=>setTimeout(r,50));
        const beforeConflict=await fs.readFile(remotePDF);
        await fs.writeFile(remotePDF,await fs.readFile(exportedPath));
        await win.webContents.executeJavaScript('runAction(save)');
        assert.equal(await win.webContents.executeJavaScript('window.pdfAnnotations.dirty()'),true,'remote conflict preserves unsaved edits');
        assert.deepEqual(await fs.readFile(remotePDF),await fs.readFile(exportedPath),'does not overwrite remote change');
        await fs.writeFile(remotePDF,beforeConflict);
        await win.webContents.executeJavaScript('runAction(save)');
        changed=await PDFDocument.load(await fs.readFile(remotePDF));
        assert.equal(changed.getPage(0).node.lookup(PDFName.of('Annots'),PDFArray).size(),0,'clear saved annotations persisted');
        await win.webContents.executeJavaScript("runAction(() => openFile({ path: '/产品设计/笔记.md', name: '笔记.md' }))");
        assert.equal(await win.webContents.executeJavaScript("state.pdfUrl === null && document.getElementById('pdfPane').hidden && !editorEl.readOnly"), true);
        dialog.showOpenDialog = originalOpenDialog;
        await win.webContents.executeJavaScript('window.mdAPI.clearConnection()');
        assert.equal(await win.webContents.executeJavaScript('window.mdAPI.loadConnection().then(res => res.data)'), null);
        console.log('UI_E2E_OK: formatting, auto-save, file operations, import, PDF export');
      } catch (err) { console.error(err); process.exitCode = 1; }
      finally {
        clearTimeout(timeout);
        await server.close();
        await fs.rm(root, { recursive: true, force: true });
        app.exit(process.exitCode || 0);
      }
    });
  });
  require('../electron/main.js');
})().catch(err => { console.error(err); app.exit(1); });
